import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomePattern from "@/components/home-pattern";
import { Container } from "@/components/container";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/lib/theme-context";
import { fontMono, fontDoto } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontDoto.variable} ${fontMono.variable} antialiased`}
      >
        <ThemeProvider>
          <HomePattern>
            <Header />
            <Container>
              {children}
            </Container>
          </HomePattern>
        </ThemeProvider>
      </body>
    </html>
  );
}
